// <auto-generated />
namespace HOSPITAL_MANAGEMENT_SYSTEM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AppointmentDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppointmentDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202202120908014_AppointmentDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
